# Generated by Django 2.0.2 on 2018-03-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Account')),
            ],
            options={
                'db_table': 'phone_number',
            },
        ),
    ]
