# Generated by Django 2.0.2 on 2018-03-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='account_id',
            new_name='account',
        ),
    ]
